from PyQt6.QtGui import QAction, QIcon, QKeySequence
from PyQt6.QtWidgets import QMessageBox

class ActionManager:
    def __init__(self, window, controller):
        self.win = window
        self.ctrl = controller

        self.new = QAction(QIcon("ui/icons/create.png"), "", window)
        self.open = QAction(QIcon("ui/icons/open.png"), "", window)
        self.save = QAction(QIcon("ui/icons/save.png"), "", window)
        self.save_as = QAction(QIcon("ui/icons/save.png"), "", window)
        self.exit = QAction(QIcon("ui/icons/exit.png"), "", window)

        self.undo = QAction(QIcon("ui/icons/cancel.png"), "", window)
        self.redo = QAction(QIcon("ui/icons/repeat.png"), "", window)

        self.copy = QAction(QIcon("ui/icons/copy.png"), "", window)
        self.cut = QAction(QIcon("ui/icons/cut.png"), "", window)
        self.paste = QAction(QIcon("ui/icons/insert.png"), "", window)
        self.delete = QAction("", window)
        self.select_all = QAction("", window)

        self.run = QAction(QIcon("ui/icons/launch.png"), "", window)

        self.help = QAction(QIcon("ui/icons/reference.png"), "", window)
        self.about = QAction(QIcon("ui/icons/information.png"), "", window)

        self.menu_new = QAction("", window)
        self.menu_open = QAction("", window)
        self.menu_save = QAction("", window)
        self.menu_save_as = QAction("", window)
        self.menu_exit = QAction("", window)

        self.menu_undo = QAction("", window)
        self.menu_redo = QAction("", window)
        self.menu_cut = QAction("", window)
        self.menu_copy = QAction("", window)
        self.menu_paste = QAction("", window)
        self.menu_delete = QAction("", window)
        self.menu_select_all = QAction("", window)

        self.menu_text_task = QAction("", window)
        self.menu_text_grammar = QAction("", window)
        self.menu_text_class = QAction("", window)
        self.menu_text_method = QAction("", window)
        self.menu_text_example = QAction("", window)
        self.menu_text_literature = QAction("", window)
        self.menu_text_source = QAction("", window)

        self.menu_ast_json = QAction("", window)

        self.menu_run = QAction("", window)

        self.menu_help = QAction("", window)
        self.menu_about = QAction("", window)

        self.lang_ru = QAction("Русский", window)
        self.lang_en = QAction("English", window)

        self.select_line = QAction("", window)

        self._add_shortcuts()
        self._connect()
        self.update_texts()

    def _add_shortcuts(self):
        self.menu_new.setShortcut(QKeySequence.StandardKey.New)
        self.menu_open.setShortcut(QKeySequence.StandardKey.Open)
        self.menu_save.setShortcut(QKeySequence.StandardKey.Save)
        self.menu_save_as.setShortcut("Ctrl+Shift+S")
        self.menu_undo.setShortcut(QKeySequence.StandardKey.Undo)
        self.menu_redo.setShortcut(QKeySequence.StandardKey.Redo)
        self.menu_cut.setShortcut(QKeySequence.StandardKey.Cut)
        self.menu_copy.setShortcut(QKeySequence.StandardKey.Copy)
        self.menu_paste.setShortcut(QKeySequence.StandardKey.Paste)
        self.menu_delete.setShortcut(QKeySequence.StandardKey.Delete)
        self.menu_select_all.setShortcut(QKeySequence.StandardKey.SelectAll)
        self.menu_run.setShortcut("F5")
        self.menu_help.setShortcut(QKeySequence.StandardKey.HelpContents)
        self.menu_about.setShortcut("Ctrl+I")
        self.menu_exit.setShortcut(QKeySequence.StandardKey.Quit)
        self.select_line.setShortcuts(["Ctrl+L", "Meta+L"])
        self.menu_ast_json.setShortcut("Ctrl+J")

    def update_texts(self):
        L = self.win.labels
        self.new.setText(L["new"])
        self.open.setText(L["open"])
        self.save.setText(L["save"])
        self.save_as.setText(L["save_as"])
        self.exit.setText(L["exit"])
        self.undo.setText(L["undo"])
        self.redo.setText(L["redo"])
        self.copy.setText(L["copy"])
        self.cut.setText(L["cut"])
        self.paste.setText(L["paste"])
        self.delete.setText(L["delete"])
        self.select_all.setText(L["select_all"])
        self.run.setText(L["run"])
        self.help.setText(L["help"])
        self.about.setText(L["about"])
        self.menu_new.setText(L["new"])
        self.menu_open.setText(L["open"])
        self.menu_save.setText(L["save"])
        self.menu_save_as.setText(L["save_as"])
        self.menu_exit.setText(L["exit"])
        self.menu_undo.setText(L["undo"])
        self.menu_redo.setText(L["redo"])
        self.menu_cut.setText(L["cut"])
        self.menu_copy.setText(L["copy"])
        self.menu_paste.setText(L["paste"])
        self.menu_delete.setText(L["delete"])
        self.menu_select_all.setText(L["select_all"])
        self.menu_text_task.setText(L["task"])
        self.menu_text_grammar.setText(L["grammar"])
        self.menu_text_class.setText(L["grammar_class"])
        self.menu_text_method.setText(L["method"])
        self.menu_text_example.setText(L["example"])
        self.menu_text_literature.setText(L["literature"])
        self.menu_text_source.setText(L["source"])
        self.menu_ast_json.setText(L["ast_json"])
        self.menu_run.setText(L["run"])
        self.menu_help.setText(L["help"])
        self.menu_about.setText(L["about"])

    def _connect(self):
        self.menu_new.triggered.connect(lambda: self.ctrl.file_new(self.win))
        self.menu_open.triggered.connect(lambda: self.ctrl.file_open(self.win))
        self.menu_save.triggered.connect(lambda: self.ctrl.file_save(self.win))
        self.menu_save_as.triggered.connect(lambda: self.ctrl.file_save_as(self.win))
        self.menu_exit.triggered.connect(self.win.close)
        self.new.triggered.connect(lambda: self.ctrl.file_new(self.win))
        self.open.triggered.connect(lambda: self.ctrl.file_open(self.win))
        self.save.triggered.connect(lambda: self.ctrl.file_save(self.win))
        self.save_as.triggered.connect(lambda: self.ctrl.file_save_as(self.win))
        self.exit.triggered.connect(self.win.close)
        self.undo.triggered.connect(lambda: self.win.get_editor().undo())
        self.redo.triggered.connect(lambda: self.win.get_editor().redo())
        self.copy.triggered.connect(lambda: self.win.get_editor().copy())
        self.cut.triggered.connect(lambda: self.win.get_editor().cut())
        self.paste.triggered.connect(lambda: self.win.get_editor().paste())
        self.delete.triggered.connect(lambda: self.win.get_editor().textCursor().removeSelectedText())
        self.select_all.triggered.connect(lambda: self.win.get_editor().selectAll())
        self.menu_undo.triggered.connect(lambda: self.win.get_editor().undo())
        self.menu_redo.triggered.connect(lambda: self.win.get_editor().redo())
        self.menu_cut.triggered.connect(lambda: self.win.get_editor().cut())
        self.menu_copy.triggered.connect(lambda: self.win.get_editor().copy())
        self.menu_paste.triggered.connect(lambda: self.win.get_editor().paste())
        self.menu_delete.triggered.connect(lambda: self.win.get_editor().textCursor().removeSelectedText())
        self.menu_select_all.triggered.connect(lambda: self.win.get_editor().selectAll())
        self.menu_text_task.triggered.connect(lambda: self._info(self.win.labels["task"]))
        self.menu_text_grammar.triggered.connect(lambda: self._info(self.win.labels["grammar"]))
        self.menu_text_class.triggered.connect(lambda: self._info(self.win.labels["grammar_class"]))
        self.menu_text_method.triggered.connect(lambda: self._info(self.win.labels["method"]))
        self.menu_text_example.triggered.connect(lambda: self._info(self.win.labels["example"]))
        self.menu_text_literature.triggered.connect(lambda: self._info(self.win.labels["literature"]))
        self.menu_text_source.triggered.connect(lambda: self._info(self.win.labels["source"]))
        self.menu_ast_json.triggered.connect(self.win.show_ast_json)
        self.menu_run.triggered.connect(self.win.run_scanner_action)
        self.run.triggered.connect(self.win.run_scanner_action)
        self.menu_help.triggered.connect(self.win.show_help)
        self.help.triggered.connect(self.win.show_help)
        self.menu_about.triggered.connect(lambda: self.ctrl.about(self.win, self.win.get_output()))
        self.about.triggered.connect(lambda: self.ctrl.about(self.win, self.win.get_output()))
        self.lang_ru.triggered.connect(lambda: self.win.set_language("ru"))
        self.lang_en.triggered.connect(lambda: self.win.set_language("en"))
        self.select_line.triggered.connect(self._select_current_line)

    def _info(self, text):
        QMessageBox.information(self.win, self.win.labels["info_title"], text)

    def _select_current_line(self):
        editor = self.win.get_editor()
        if editor is None:
            return
        cursor = editor.textCursor()
        cursor.select(cursor.SelectionType.LineUnderCursor)
        editor.setTextCursor(cursor)